services:
  device:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: endura-endura_sdk-device
    ports:
      - "8000:8000"
    expose:
      - "8000"
    networks:
      - monitoring
    mem_limit: 256m
    cpus: 0.5
    volumes:
      - device-data:/app/data
      - .env:/app/.env
      # - ./endura_sdk:/app/endura_sdk

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  device-data: